services:
  - type: web
    name: keystone
    env: node
    plan: starter
    buildCommand: yarn install && yarn build && yarn start
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: keystone
          property: connectionString
      - key: SESSION_SECERT
        generateValue: true

databases:
  - name: keystone
    plan: starter
